log_level: info
device_name: Pi Display
device_type: speaker
audio_backend: alsa
audio_device: default
bitrate: 320
initial_volume: 80
volume_steps: 100
ignore_last_volume: false
zeroconf_enabled: true
zeroconf_port: 0
zeroconf_backend: avahi
credentials:
  type: zeroconf
  zeroconf:
    persist_credentials: false
server:
  enabled: true
  address: 127.0.0.1
  port: 3678
  image_size: large
mpris_enabled: false
